default_language_version:
    python: python3.11
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./backend/setup.cfg backend
        language: system
        types: [ python ]
        pass_filenames: false
        args: ['--verbose']

      - id: black
        name: black
        entry: black --skip-string-normalization --config ./backend/pyproject.toml backend
        language: system
        types: [ python ]
        pass_filenames: false
        args: ['--verbose']

      - id: flake8
        name: flake8
        entry: flake8 --config ./backend/setup.cfg backend
        language: system
        types: [ python ]
        pass_filenames: false
        args: ['--verbose']
