services:
  backend:
    env_file:
      - path: .env
        required: true
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - db

  bot:
    env_file:
      - path: .env
        required: true
    build:
      context: ../bot
      dockerfile: Dockerfile
    depends_on:
      - db

  db:
    env_file:
      - path: .env
        required: true
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginxinc/nginx-unprivileged:1.26.1-alpine
    volumes:
      - static_data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - backend
    ports:
      - "8000:80"

networks:
  default:
    name: wb_bears_network

volumes:
  db_data:
  static_data:
