default_language_version:
    python: python3.11
repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --settings-file ./bot/setup.cfg bot
        language: system
        types: [ python ]
        pass_filenames: false
        args: ['--verbose']

      - id: black
        name: black
        entry: black --skip-string-normalization --config ./bot/pyproject.toml bot
        language: system
        types: [ python ]
        pass_filenames: false
        args: ['--verbose']

      - id: flake8
        name: flake8
        entry: flake8 --config ./bot/setup.cfg bot
        language: system
        types: [ python ]
        pass_filenames: false
        args: ['--verbose']
